//! Build-script inventory generation. Input bytes are snapshotted into `OUT_DIR`
//! so the manifest and `include_bytes!` always describe the same resource bytes.

use crate::{
    AssetManifest, AssetRecord, DirectoryAssets, MANIFEST_FORMAT, MAX_FILES, MAX_TOTAL_BYTES,
    content_type, safe_relative, sha256,
};
use anyhow::{Context, Result, ensure};
use std::{env, fs, path::Path};

/// Generate `OUT_DIR/xcss-web-assets.rs`, exporting `ASSETS`, `MANIFEST`, and `DIGEST`.
/// Cargo watches the source directories and files, including additions/removals.
pub fn generate(root: impl AsRef<Path>) -> Result<()> {
    generate_to(root, "xcss-web-assets.rs")
}

/// Generate a separately named source file, useful for independent Web entry points.
/// Each included module exports the same three names. `filename` must be one safe name.
pub fn generate_to(root: impl AsRef<Path>, filename: &str) -> Result<()> {
    let output = env::var_os("OUT_DIR").context("OUT_DIR is required in a Cargo build script")?;
    generate_at(root.as_ref(), Path::new(&output), filename)
}

/// Explicit output location for build tools and acceptance tests; no environment mutation.
pub fn generate_at(root: &Path, output: &Path, filename: &str) -> Result<()> {
    ensure!(
        safe_relative(filename) && !filename.contains('/'),
        "unsafe generated source filename"
    );
    let root = if root.is_absolute() {
        root.to_path_buf()
    } else {
        env::current_dir()?.join(root)
    };
    let directory = DirectoryAssets::new(&root)?;
    let paths = collect_paths(&root, true)?;
    ensure!(!paths.is_empty(), "web asset directory is empty");
    fs::create_dir_all(output)?;
    let snapshots = output.join(format!("{filename}.assets"));
    fs::create_dir_all(&snapshots)?;
    let mut files = Vec::with_capacity(paths.len());
    let mut declarations = String::from(
        "// Generated by xcss-web-assets; do not edit.\npub static ASSETS: &[xcss_web_assets::EmbeddedAsset] = &[\n",
    );
    let mut total = 0_u64;
    for (index, path) in paths.iter().enumerate() {
        let bytes = directory
            .read(path)
            .with_context(|| format!("read web asset {path}"))?;
        total = total
            .checked_add(bytes.len() as u64)
            .context("web asset byte overflow")?;
        ensure!(
            total <= MAX_TOTAL_BYTES,
            "web asset directory exceeds budget"
        );
        let digest = sha256(&bytes);
        let snapshot = snapshots.join(format!("{index:05}-{digest}"));
        // The source can change after this read; compilation uses this exact snapshot.
        fs::write(&snapshot, &bytes)?;
        let snapshot = fs::canonicalize(snapshot)?;
        let snapshot = snapshot
            .to_str()
            .context("generated asset path must be UTF-8")?;
        let mime = content_type(path);
        declarations.push_str(&format!("    xcss_web_assets::EmbeddedAsset {{ path: {path:?}, content_type: {mime:?}, bytes: include_bytes!({snapshot:?}), sha256: {digest:?} }},\n"));
        files.push(AssetRecord {
            path: path.clone(),
            content_type: mime.to_owned(),
            size: bytes.len() as u64,
            sha256: digest,
        });
    }
    declarations.push_str("];\n");
    let manifest = serde_json::to_string(&AssetManifest {
        format: MANIFEST_FORMAT.to_owned(),
        files,
    })?;
    let digest = sha256(manifest.as_bytes());
    declarations.push_str(&format!(
        "pub const MANIFEST: &str = {manifest:?};\npub const DIGEST: &str = {digest:?};\n"
    ));
    fs::write(output.join(filename), declarations)?;
    fs::write(output.join(format!("{filename}.manifest.json")), manifest)?;
    Ok(())
}

pub(crate) fn collect_paths(root: &Path, watch: bool) -> Result<Vec<String>> {
    let mut paths = Vec::new();
    let mut visited = 0_usize;
    collect(root, root, &mut paths, &mut visited, watch)?;
    paths.sort();
    Ok(paths)
}

fn collect(
    root: &Path,
    directory: &Path,
    paths: &mut Vec<String>,
    visited: &mut usize,
    watch: bool,
) -> Result<()> {
    if watch {
        println!("cargo:rerun-if-changed={}", directory.display());
    }
    for entry in fs::read_dir(directory)? {
        *visited += 1;
        ensure!(
            *visited <= MAX_FILES,
            "web asset inventory exceeds entry budget"
        );
        let entry = entry?;
        let path = entry.path();
        let relative = path
            .strip_prefix(root)?
            .to_str()
            .context("web asset path must be UTF-8")?
            .replace(std::path::MAIN_SEPARATOR, "/");
        ensure!(
            safe_relative(&relative),
            "unsafe web asset path: {relative}"
        );
        let metadata = fs::symlink_metadata(&path)?;
        ensure!(
            !metadata.file_type().is_symlink(),
            "web asset symlink is forbidden: {relative}"
        );
        if metadata.is_dir() {
            collect(root, &path, paths, visited, watch)?;
        } else {
            ensure!(metadata.is_file(), "web asset must be regular: {relative}");
            #[cfg(unix)]
            {
                use std::os::unix::fs::MetadataExt;
                ensure!(
                    metadata.nlink() == 1,
                    "web asset hardlink is forbidden: {relative}"
                );
            }
            if watch {
                println!("cargo:rerun-if-changed={}", path.display());
            }
            paths.push(relative);
        }
    }
    Ok(())
}
