from __future__ import annotations

import tempfile
import unittest
import sys
from pathlib import Path

TOOLS = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(TOOLS))

from sarmg_schema_compose import ComposeError, compose, write_output  # noqa: E402


class SchemaComposerTests(unittest.TestCase):
    def test_control_plane_order_is_deterministic(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            product = Path(directory) / "product.sql"
            product.write_text(
                "CREATE TABLE widgets (id INTEGER PRIMARY KEY);\n"
                "CREATE INDEX widgets_id_idx ON widgets(id);\n",
                encoding="utf-8",
            )
            first = compose("server-control-plane", ["admin-persistent"], product)
            second = compose("server-control-plane", ["admin-persistent"], product)
            self.assertEqual(first, second)
            self.assertTrue(
                first.startswith("-- Generated by sarmg-schema-compose; DO NOT EDIT.\n")
            )
            self.assertLess(first.index("CREATE TABLE product_metadata"), first.index("_sarmg_platform_metadata"))
            self.assertLess(first.index("_sarmg_platform_metadata"), first.index("_sarmg_administrators"))
            self.assertLess(first.index("CREATE TABLE widgets"), first.index("CREATE INDEX _sarmg_admin"))
            self.assertLess(first.index("CREATE INDEX _sarmg_admin"), first.index("CREATE INDEX widgets"))

    def test_product_cannot_claim_reserved_objects(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            product = Path(directory) / "product.sql"
            product.write_text("CREATE TABLE _sarmg_owned(id INTEGER);\n", encoding="utf-8")
            with self.assertRaisesRegex(ComposeError, "reserved"):
                compose("server-control-plane", [], product)

    def test_check_rejects_stale_generated_file(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            product = root / "product.sql"
            output = root / "generated/current_schema.sql"
            product.write_text("CREATE TABLE items(id INTEGER);\n", encoding="utf-8")
            content = compose("server-control-plane", [], product)
            write_output(output, content, check=False)
            write_output(output, content, check=True)
            output.write_text("stale\n", encoding="utf-8")
            with self.assertRaisesRegex(ComposeError, "stale"):
                write_output(output, content, check=True)


if __name__ == "__main__":
    unittest.main()
