"""Deterministic current-schema composer for Sarmg products."""

from __future__ import annotations

import argparse
import os
import re
import sqlite3
import tempfile
import tomllib
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, Sequence


FOUNDATION_ROOT = Path(__file__).resolve().parents[1]
PROFILE_IDS = {
    "server-control-plane",
    "server-filesystem",
    "desktop-agent",
    "mobile-agent",
    "offline-tool",
    "web-react-admin",
    "web-embedded-native",
}
CAPABILITY_DDL = {
    "admin-persistent": FOUNDATION_ROOT / "schemas/admin/persistent-v1.sql",
}
PLATFORM_PROFILES = {"server-control-plane"}
RESERVED_PREFIX = "_sarmg_"
GENERATED_NOTICE = "-- Generated by sarmg-schema-compose; DO NOT EDIT."


class ComposeError(RuntimeError):
    """The requested schema cannot be composed safely."""


@dataclass(frozen=True)
class Statement:
    kind: str
    sql: str


def _read_sql(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except (OSError, UnicodeError) as error:
        raise ComposeError(f"{path}: cannot read UTF-8 SQL: {error}") from error


def _split_sql(source: str, path: Path) -> list[str]:
    statements: list[str] = []
    buffer = ""
    for line in source.splitlines(keepends=True):
        buffer += line
        if sqlite3.complete_statement(buffer):
            statement = buffer.strip()
            if statement:
                statements.append(statement.removesuffix(";").rstrip())
            buffer = ""
    if buffer.strip():
        raise ComposeError(f"{path}: final SQL statement is incomplete or lacks ';'")
    return statements


def _without_leading_comments(statement: str) -> str:
    value = statement.lstrip()
    while True:
        if value.startswith("--"):
            _, separator, value = value.partition("\n")
            if not separator:
                return ""
            value = value.lstrip()
            continue
        if value.startswith("/*"):
            end = value.find("*/", 2)
            if end < 0:
                return ""
            value = value[end + 2 :].lstrip()
            continue
        return value


def _classify(statement: str, path: Path) -> Statement:
    meaningful = _without_leading_comments(statement)
    patterns = (
        ("table", r"CREATE\s+(?:VIRTUAL\s+)?TABLE\b"),
        ("index", r"CREATE\s+(?:UNIQUE\s+)?INDEX\b"),
        ("trigger", r"CREATE\s+TRIGGER\b"),
    )
    for kind, pattern in patterns:
        if re.match(pattern, meaningful, re.IGNORECASE):
            return Statement(kind, statement)
    raise ComposeError(
        f"{path}: current schema may contain only CREATE TABLE/INDEX/TRIGGER statements"
    )


def _statements(path: Path) -> list[Statement]:
    return [_classify(value, path) for value in _split_sql(_read_sql(path), path)]


def _profile_capabilities(profile: str) -> set[str]:
    if profile not in PROFILE_IDS:
        raise ComposeError(f"unknown profile: {profile}")
    path = FOUNDATION_ROOT / "profiles" / f"{profile}.toml"
    try:
        value = tomllib.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeError, tomllib.TOMLDecodeError) as error:
        raise ComposeError(f"{path}: cannot load profile: {error}") from error
    return set(value.get("required_capabilities", [])) | set(
        value.get("optional_capabilities", [])
    )


def _validate_capabilities(profile: str, capabilities: Sequence[str]) -> tuple[str, ...]:
    if len(set(capabilities)) != len(capabilities):
        raise ComposeError("capabilities must not be repeated")
    allowed = _profile_capabilities(profile)
    unknown = sorted(set(capabilities) - allowed)
    if unknown:
        raise ComposeError(
            f"profile {profile} does not permit capabilities: {', '.join(unknown)}"
        )
    unsupported = sorted(
        capability
        for capability in capabilities
        if capability not in CAPABILITY_DDL and capability.endswith(("-persistent", "-sqlite"))
    )
    if unsupported:
        raise ComposeError(
            "no current DDL is registered for capabilities: " + ", ".join(unsupported)
        )
    return tuple(sorted(capabilities))


def _reject_product_reserved_objects(product_sql: str, product_path: Path) -> None:
    connection = sqlite3.connect(":memory:")
    try:
        connection.executescript(product_sql)
        objects = connection.execute(
            "SELECT type, name FROM sqlite_schema "
            "WHERE name = 'product_metadata' OR name GLOB '_sarmg_*' "
            "ORDER BY type, name"
        ).fetchall()
    except sqlite3.Error as error:
        raise ComposeError(f"{product_path}: invalid product DDL: {error}") from error
    finally:
        connection.close()
    if objects:
        rendered = ", ".join(f"{kind} {name}" for kind, name in objects)
        raise ComposeError(
            f"{product_path}: product DDL uses Foundation-reserved objects: {rendered}"
        )


def _validate_complete_schema(sql: str) -> None:
    connection = sqlite3.connect(":memory:")
    try:
        connection.execute("PRAGMA foreign_keys=ON")
        connection.executescript(sql)
        violations = connection.execute("PRAGMA foreign_key_check").fetchall()
    except sqlite3.Error as error:
        raise ComposeError(f"generated schema is invalid: {error}") from error
    finally:
        connection.close()
    if violations:
        raise ComposeError(f"generated schema has foreign-key violations: {violations!r}")


def compose(profile: str, capabilities: Sequence[str], product_path: Path) -> str:
    capabilities = _validate_capabilities(profile, capabilities)
    product_sql = _read_sql(product_path)
    _reject_product_reserved_objects(product_sql, product_path)

    sections: list[tuple[str, list[Statement]]] = [
        (
            "product metadata",
            _statements(FOUNDATION_ROOT / "schemas/product-metadata/v1.sql"),
        )
    ]
    if profile in PLATFORM_PROFILES:
        sections.append(
            ("platform metadata", _statements(FOUNDATION_ROOT / "schemas/platform/v1.sql"))
        )
    for capability in capabilities:
        ddl = CAPABILITY_DDL.get(capability)
        if ddl is not None:
            sections.append((f"capability: {capability}", _statements(ddl)))
    sections.append(("product", _statements(product_path)))

    ordered: list[tuple[str, Statement]] = []
    for kind in ("table", "index", "trigger"):
        for section, statements in sections:
            ordered.extend((section, statement) for statement in statements if statement.kind == kind)

    lines = [
        GENERATED_NOTICE,
        f"-- profile: {profile}",
        f"-- capabilities: {','.join(capabilities) if capabilities else '-'}",
        "",
    ]
    previous_section: str | None = None
    for section, statement in ordered:
        if section != previous_section:
            if previous_section is not None:
                lines.append("")
            lines.append(f"-- {section}")
            previous_section = section
        lines.extend((statement.sql + ";", ""))
    result = "\n".join(lines).rstrip() + "\n"
    _validate_complete_schema(result)
    return result


def write_output(path: Path, content: str, check: bool) -> None:
    if check:
        try:
            current = path.read_text(encoding="utf-8")
        except (OSError, UnicodeError) as error:
            raise ComposeError(f"{path}: cannot check generated schema: {error}") from error
        if current != content:
            raise ComposeError(f"{path}: generated schema is stale; regenerate it")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary_name = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    temporary = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as stream:
            stream.write(content)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary, path)
    except BaseException:
        temporary.unlink(missing_ok=True)
        raise


def parser() -> argparse.ArgumentParser:
    result = argparse.ArgumentParser(prog="sarmg-schema-compose")
    result.add_argument("--profile", required=True, choices=sorted(PROFILE_IDS))
    result.add_argument("--capability", action="append", default=[])
    result.add_argument("--product", required=True, type=Path)
    result.add_argument("--output", required=True, type=Path)
    result.add_argument("--check", action="store_true")
    return result


def main(arguments: Iterable[str] | None = None) -> int:
    options = parser().parse_args(arguments)
    try:
        content = compose(options.profile, options.capability, options.product)
        write_output(options.output, content, options.check)
    except ComposeError as error:
        parser().error(str(error))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
